import { type Answers, type GeneratedFile } from './answers.js';

// --- helpers ---------------------------------------------------------------

/** YAML single-quoted scalar (keeps empty strings explicit as ''). */
function quote(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

/** Shared instance config as KEY=value lines for a .env / .dev.vars file. */
function envLines(a: Answers, opts: { forCloudflare?: boolean } = {}): string[] {
  const lines: string[] = [];
  if (!opts.forCloudflare) {
    // PORT is a host-side publish port only. docker-compose maps
    // ${PORT:-8787}:8787 and the container always listens on 8787, so PORT is
    // deliberately NOT injected here (injecting it would move the listener off
    // 8787 and break the published mapping). Republish elsewhere from the shell:
    //   PORT=9000 docker compose up -d
    lines.push('# PORT is the host publish port only — set it in your shell, e.g.');
    lines.push('#   PORT=9000 docker compose up -d');
    lines.push('# It is not injected into the container, which always listens on 8787.');
  }
  lines.push(`AUTH=${a.auth}`);
  lines.push(`BASE_HOST=${a.baseHost}`);
  lines.push('VISIBILITY=private');
  if (a.auth === 'google') {
    lines.push('# Fill these in (AUTH=google):');
    lines.push('SESSION_SECRET=');
    lines.push('GOOGLE_CLIENT_ID=');
    lines.push('GOOGLE_CLIENT_SECRET=');
    if (!a.allowedEmailDomains) {
      lines.push('# WARNING: an empty allowlist admits ANY Google account — set a domain below.');
    }
    lines.push(`ALLOWED_EMAIL_DOMAINS=${a.allowedEmailDomains}`);
    lines.push('DEPLOY_TOKEN=');
  }
  lines.push('# Optional AI pass-through:');
  lines.push('ANTHROPIC_API_KEY=');
  if (!opts.forCloudflare) {
    lines.push(`STORAGE=${a.storage}`);
    lines.push('SQLITE_PATH=/data/brisk.sqlite');
    lines.push('FS_ROOT=/data/objects');
    if (a.storage === 's3' && a.s3) {
      lines.push(`S3_ENDPOINT=${a.s3.endpoint}`);
      lines.push(`S3_BUCKET=${a.s3.bucket}`);
      lines.push(`S3_REGION=${a.s3.region}`);
      lines.push('S3_ACCESS_KEY_ID=');
      lines.push('S3_SECRET_ACCESS_KEY=');
    }
  }
  return lines;
}

// --- docker compose --------------------------------------------------------

function composeFiles(a: Answers): GeneratedFile[] {
  const minio =
    a.storage === 's3'
      ? `
  minio:
    image: minio/minio:latest
    command: server /data --console-address ':9001'
    restart: unless-stopped
    ports: ['9000:9000', '9001:9001']
    environment:
      MINIO_ROOT_USER: \${S3_ACCESS_KEY_ID:-minioadmin}
      MINIO_ROOT_PASSWORD: \${S3_SECRET_ACCESS_KEY:-minioadmin}
    volumes: [minio-data:/data]`
      : '';
  const minioVol = a.storage === 's3' ? '\n  minio-data:' : '';
  const compose = `# Generated by create-brisk. Edit .env for configuration.
services:
  brisk:
    image: ${a.image}
    restart: unless-stopped
    env_file: [.env]
    ports: ['\${PORT:-8787}:8787']
    volumes: [brisk-data:/data]${minio}

volumes:
  brisk-data:${minioVol}
`;
  return [
    { path: 'docker-compose.yml', content: compose },
    { path: '.env', content: envLines(a).join('\n') + '\n' },
  ];
}

// --- kubernetes (helm values) ---------------------------------------------

function kubernetesFiles(a: Answers): GeneratedFile[] {
  const [repository, tag] = a.image.split(':');
  const s3Block =
    a.storage === 's3' && a.s3
      ? `
s3:
  endpoint: ${a.s3.endpoint}
  bucket: ${a.s3.bucket}
  region: ${a.s3.region}`
      : '';
  // AUTH=google admits anyone Google authenticates when the allowlist is empty
  // (worker isAllowedEmail). Emit the key with a loud warning so an internet-
  // reachable Ingress isn't left open to every Google account by default.
  const allowlistBlock =
    a.auth === 'google'
      ? `\n  # WARNING: an empty allowlist admits ANY Google account. Set at least one of
  # these (or pass --set config.allowedEmailDomains=yourco.com at install time)
  # before exposing this instance on a public Ingress.
  allowedEmailDomains: ${quote(a.allowedEmailDomains)}
  allowedEmails: ''`
      : '';
  const ingressOn = a.baseHost ? 'true' : 'false';
  const values = `# Generated by create-brisk. helm install brisk <chart> -f brisk-values.yaml
# Secrets are NOT inlined here — pass them with --set secrets.* or set existingSecret.
replicaCount: 1 # in-process realtime; >1 needs the Redis backplane (not yet shipped)

image:
  repository: ${repository}
  tag: ${tag ?? 'latest'}

config:
  baseHost: ${a.baseHost}
  auth: ${a.auth}
  visibility: private${allowlistBlock}
  storage: ${a.storage}${s3Block}

ingress:
  enabled: ${ingressOn}
  host: ${a.baseHost || 'brisk.example.com'}
  wildcard: true
  tls:
    enabled: ${ingressOn}
    secretName: brisk-tls

persistence:
  enabled: true
  size: 8Gi
`;
  return [{ path: 'brisk-values.yaml', content: values }];
}

// --- cloudflare ------------------------------------------------------------

function cloudflareFiles(a: Answers): GeneratedFile[] {
  const devVars = envLines(a, { forCloudflare: true }).join('\n') + '\n';
  const allowlistVar =
    a.auth === 'google'
      ? `- ALLOWED_EMAIL_DOMAINS = ${
          a.allowedEmailDomains ||
          'your-company.com   # ⚠ REQUIRED: an empty allowlist admits ANY Google account'
        }\n`
      : '';
  const checklist = `# Deploying Brisk to Cloudflare

Local dev vars are in \`worker/.dev.vars\` (\`wrangler dev\` reads it from the
\`worker/\` directory, so it must live there — not the repo root).

## Dashboard variables (Workers & Pages → your worker → Settings → Variables)
- BASE_HOST = ${a.baseHost || '(unset → path-mode /s/<site>/)'}
- AUTH = ${a.auth}
- VISIBILITY = private
${allowlistVar}
## Secrets (\`wrangler secret put <NAME>\`)
${a.auth === 'google' ? '- wrangler secret put SESSION_SECRET\n- wrangler secret put GOOGLE_CLIENT_ID\n- wrangler secret put GOOGLE_CLIENT_SECRET\n- wrangler secret put DEPLOY_TOKEN   # optional, for CI\n' : '(none required for AUTH=none)\n'}- wrangler secret put ANTHROPIC_API_KEY   # optional, powers brisk.ai

## Resources + deploy
    npx wrangler d1 create brisk        # paste the id into worker/wrangler.jsonc
    npx wrangler r2 bucket create brisk
    npx wrangler d1 migrations apply brisk --remote
    pnpm --filter @usebrisk/sdk build
    npx wrangler deploy
${a.baseHost ? `\n## Wildcard subdomains\nAttach \`${a.baseHost}\` + route \`*.${a.baseHost}/*\` in the dashboard; add a wildcard DNS record and a cert covering \`*.${a.baseHost}\`. See the repo README → Wildcard subdomains.\n` : ''}`;
  return [
    { path: 'worker/.dev.vars', content: devVars },
    { path: 'BRISK-CLOUDFLARE.md', content: checklist },
  ];
}

// --- public API ------------------------------------------------------------

export function generate(a: Answers): GeneratedFile[] {
  switch (a.target) {
    case 'compose':
      return composeFiles(a);
    case 'kubernetes':
      return kubernetesFiles(a);
    case 'cloudflare':
      return cloudflareFiles(a);
  }
}

export function nextSteps(a: Answers): string[] {
  const steps: string[] = [];
  if (a.auth === 'none') {
    steps.push('⚠  AUTH=none serves an OPEN backend — only run this on a trusted network.');
  }
  if (a.auth === 'google' && !a.allowedEmailDomains) {
    steps.push('⚠  AUTH=google with an empty allowlist admits ANY Google account — set an allowed');
    steps.push('   email domain (see the generated config) before exposing this instance.');
  }
  switch (a.target) {
    case 'compose':
      steps.push('Fill in the secrets in .env, then bring the stack up:');
      steps.push('  docker compose up -d');
      steps.push('  open http://localhost:8787');
      break;
    case 'kubernetes':
      steps.push('Install the chart (from a checkout of the brisk repo):');
      steps.push(
        '  helm install brisk ./deploy/helm/brisk -f brisk-values.yaml \\\n' +
          (a.auth === 'google'
            ? '    --set secrets.sessionSecret=$(openssl rand -hex 32) \\\n    --set secrets.googleClientId=… --set secrets.googleClientSecret=…'
            : '    # AUTH=none needs no secrets'),
      );
      if (a.auth === 'google')
        steps.push(
          '  # Restrict logins to your domain (an empty allowlist admits ANY Google account):\n' +
            '  #   --set config.allowedEmailDomains=yourco.com',
        );
      if (a.storage === 's3')
        steps.push('  # set secrets.s3AccessKeyId / s3SecretAccessKey for your bucket');
      break;
    case 'cloudflare':
      steps.push(
        'Follow BRISK-CLOUDFLARE.md: set the dashboard vars + secrets, then `wrangler deploy`.',
      );
      break;
  }
  return steps;
}
